### ISSUE TITLE
Let's make main the new default branch

### ISSUE THREAD

**Issue by fulv** [collective/awesome-plone#6]
See https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md

**Comment by fulv** [comment]
I don't have access to the settings of this repo.

**Comment by cekk** [comment]
me neither

**Comment by fulv** [comment]
@cekk but you made the initial commit.  Who owns this repo, if not you?

**Comment by fulv** [comment]
@tkimnguyen? @espenmn? anyone?

**Comment by pbauer** [comment]
done
